### ISSUE TITLE
Clean obj/Layout folder content.

### ISSUE THREAD

**Issue by jzeferino** [dotnet-ad/AutoFindViews#2]
Would be nice to have the obj/Layout folder content cleaned when we do a `Clean`.

Do you agree?

**Comment by aloisdeniel** [comment]
Added this to a new version on NuGet, with your other suggestion. 

[![NuGet](https://img.shields.io/nuget/v/AutoFindViews.svg?label=NuGet)](https://www.nuget.org/packages/AutoFindViews/)
